### ISSUE TITLE
Define the apollo-server schema

### ISSUE THREAD

**Issue by fanny** [panelinhadees/server#10]
**Is your feature request related to a problem? Please describe.**
Since we have, the nodes, relationships and resolves, we can define our schema.

**Describe the solution you'd like**
I would like to see a complete definition of schema, for this sprint

**Related**
(#8 and #9)

**Comment by jadsonluan** [comment]
This issue was closed by mistake, my bad. The expected has #7

**Comment by LukeHxH** [comment]
@fanny @jadsonluan Don't you think that it's better to work with interfaces, like RepositoryOwner? Because if we need to change something about the query in the future, it'll be better to do it and will require a smaller time of work.

For example:

```gql
query getRepoOwner($login: String!){
    RepositoryOwner(login: $login) {
        ... on User {
            name
        }
        ... on Organization {
            name
        } 
    }
}
```

This query can be used to find a organization or a user, and we won't need to make two queries like `getUser` or `getRepository`. That's why suggested [RepositoryOwner](https://developer.github.com/v4/interface/repositoryowner/). This interface is implemented by [Organization ](https://developer.github.com/v4/object/organization/)and [User](https://developer.github.com/v4/object/user/).
