### ISSUE TITLE
Define the data required for our apollo-server schema

### ISSUE THREAD

**Issue by fanny** [panelinhadees/server#8]
**Is your feature request related to a problem? Please describe.**
how do we use the github data, and act as an interface to the front, it's necessary to define which data we will use in this sprint 

**Describe the solution you'd like**
I would like have a discussion to define this.

**Describe alternatives you've considered**
We could do the discussion in this issue, because then we can have all this saved, in slack we risk losing

**Comment by LukeHxH** [comment]
From what I've studied from the Github v4 API, we'll need the information provided from the "RepositoryOwner" interface (which is implemented by "Organization" and "User" objects), as well as all the queries that return a RepositoryOwner object.

**Comment by fanny** [comment]
Hi, @LukeHxH, i think that is enough get [Organization](https://developer.github.com/v4/object/organization/), it's already provides the basic infos about org, and your relationships like: teams, repos. And for this sprint, this is enough.

**Comment by jadsonluan** [comment]
I agree with @fanny

**Comment by LukeHxH** [comment]
@fanny @jadsonluan Don't you think that it's better to work with interfaces, like RepositoryOwner? Because if we need to change something about the query in the future, it'll be better to do it and will require a smaller time of work.

For example:

```gql
query getRepoOwner($login: String!){
    RepositoryOwner(login: $login) {
        ... on User {
            name
        }
        ... on Organization {
            name
        } 
    }
}
```

This query can be used to find a organization or a user, and we won't need to make two queries like `getUser` or `getRepository`. That's why suggested [RepositoryOwner](https://developer.github.com/v4/interface/repositoryowner/). This interface is implemented by [Organization ](https://developer.github.com/v4/object/organization/)and [User](https://developer.github.com/v4/object/user/).

**Comment by fanny** [comment]
Humm, sounds good for me!

**Comment by jadsonluan** [comment]
Understood! You can go ahead.
